name: Build & Publish

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "echo 'The build job is triggered...'"

  publish-gpr:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: "echo 'The publish-gpr job is triggered...'"
