name: Create Release and Publish Packages
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Maven release package
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: ${{ github.ref_name }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          JAVA_HOME: /usr/lib/jvm/java-21-openjdk/