name: Publish package to GitHub Packages
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          overwrite-settings: true
          server-id: 'github'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Maven release package
        run: | 
          ./mvnw release:prepare release:perform -DreleaseCommitPrefix=${{ env.GITHUB_ACTOR }}
        env:
          MAVEN_USERNAME: ${{ env.GITHUB_ACTOR }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
